### ISSUE TITLE
0.7.3 stopped working for me

### ISSUE THREAD

**Issue by herzi** [VeniceX/File#18]
While 0.7.2 was compiling properly, 0.7.3 fails with this error:

           /tmp/staged/app/Packages/File-0.7.3/Sources/File.swift:258:34: error: value of optional type 'OpaquePointer?' not unwrapped; did you mean to use '!' or '?'?
                   while let file = readdir(dir) {
                                            ^
                                               !

**Comment by Danappelxx** [comment]
What platform and snapshot is this with? Cc @donut

**Comment by donut** [comment]
I did change that method (`contentsOfDirectory()`), copying it mostly from Quark's implementation. On snapshot 05-09 I was getting runtime errors. Using Quark's implementation worked for me and passes the tests, but I did not test it on Linux, only OS X 10.11.6.

**Comment by herzi** [comment]
This is on Linux w/ Swift 2016-05-09a.

**Comment by donut** [comment]
Can you try editing your local copy of [Packages/File-0.7.3/Sources/File.swift] so that line 257 reads `while let file = readdir(dir!) {` (adding `!` to force unwrap the optional)? I'm going to test it on a Linux box as well, but this is working fine on OS X.

**Comment by donut** [comment]
I just pushed 0.7.4 with the above fix. Please test it out and let me know if it resolves your issue or not. Sorry about breaking things for you.

**Comment by donut** [comment]
herzi confirmed it's working on slack.
